### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by zazinio** [dwalton76/rubiks-cube-tracker#5]
hi 
i am noob i had run your program 
for my school project and run pretty well
but reinstall raspberry and i install everything
without errors by instructions left.
and now when i start the program and when it see rubik's cube
show me some errors like this  
`pi@raspberrypi:~ $ rubiks-cube-tracker.py --webcam 0
Traceback (most recent call last):
  File "/usr/local/bin/rubiks-cube-tracker.py", line 49, in <module>
    rvid.analyze_webcam()
  File "/usr/local/lib/python2.7/dist-packages/rubikscubetracker/__init__.py", line 1711, in analyze_webcam
    if self.analyze(webcam=True):
  File "/usr/local/lib/python2.7/dist-packages/rubikscubetracker/__init__.py", line 1417, in analyze
    missing = self.find_missing_squares(missing_count)
  File "/usr/local/lib/python2.7/dist-packages/rubikscubetracker/__init__.py", line 1202, in find_missing_squares
    self.set_contour_row_col_index(con)
  File "/usr/local/lib/python2.7/dist-packages/rubikscubetracker/__init__.py", line 979, in set_contour_row_col_index
    row_size = round(cube_height / float(self.median_square_width + self.black_border_width))
ZeroDivisionError: float division by zero
pi@raspberrypi:~ $ rubiks-cube-tracker.py --webcam 0
Traceback (most recent call last):
  File "/usr/local/bin/rubiks-cube-tracker.py", line 49, in <module>
    rvid.analyze_webcam()
  File "/usr/local/lib/python2.7/dist-packages/rubikscubetracker/__init__.py", line 1711, in analyze_webcam
    if self.analyze(webcam=True):
  File "/usr/local/lib/python2.7/dist-packages/rubikscubetracker/__init__.py", line 1407, in analyze
    self.get_black_border_width()
  File "/usr/local/lib/python2.7/dist-packages/rubikscubetracker/__init__.py", line 1050, in get_black_border_width
    "black_border_width %s, median_square_width %s" % (self.black_border_width, self.median_square_width)
AssertionError: black_border_width 23, median_square_width 15
`

**Comment by zazinio** [comment]
I have try it by
git clone https://github.com/dwalton76/rubiks-cube-tracker.git
cd rubiks-cube-tracker
git checkout 3fcf92a0a47aa84800d01f66b50e5131799dbc5b
sudo python2 setup.py install
and install rubiks-color-resolver
and Install solvers by instructions
but now error is
pi@raspberrypi:~ $ rubiks-cube-tracker.py --webcam 0
2019-05-12 21:41:29,583            __init__.py     INFO: Saved side F, 9 squares
2019-05-12 21:41:55,090            __init__.py     INFO: Saved side R, 9 squares
2019-05-12 21:42:05,990            __init__.py     INFO: Saved side B, 9 squares
2019-05-12 21:43:18,331            __init__.py     INFO: Saved side L, 9 squares
2019-05-12 21:44:09,735            __init__.py     INFO: Saved side U, 9 squares
2019-05-12 21:44:19,378            __init__.py     INFO: Saved side D, 9 squares
2019-05-12 21:44:19,384            __init__.py     INFO: rubiks-color-resolver.py --json --filename /tmp/webcam.json
Traceback (most recent call last):
  File "/usr/local/bin/rubiks-color-resolver.py", line 4, in <module>
    __import__('pkg_resources').run_script('rubikscolorresolver==1.0.0', 'rubiks-color-resolver.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1486, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'rubiks-color-resolver.py'
Traceback (most recent call last):
  File "/usr/local/bin/rubiks-cube-tracker.py", line 4, in <module>
    __import__('pkg_resources').run_script('rubikscubetracker==1.0.0', 'rubiks-cube-tracker.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/rubikscubetracker-1.0.0-py2.7.egg/EGG-INFO/scripts/rubiks-cube-tracker.py", line 49, in <module>
    
  File "build/bdist.linux-armv7l/egg/rubikscubetracker/__init__.py", line 1685, in analyze_webcam
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['rubiks-color-resolver.py', '--json', '--filename', '/tmp/webcam.json']' returned non-zero exit status 1

**Comment by dwalton76** [comment]
Looks like you missed this step in the readme

Installing rubiks-color-resolver

Follow the instructions at https://github.com/dwalton76/rubiks-color-resolver to install the rubiks-color-resolver library
