### ISSUE TITLE
This photo fails an assert

### ISSUE THREAD

**Issue by CleoQc** [dwalton76/rubiks-cube-tracker#6]
This photo fails an assert . Any idea why?  All other faces are good to go. 

```
pi@raspberrypi:~/brickuber $ rubiks-cube-tracker.py --filename ./BricKuber_back_face.jpg
2020-03-24 15:02:16,739            __init__.py     INFO: Analyze ./BricKuber_back_face.jpg
Traceback (most recent call last):
  File "/usr/local/bin/rubiks-cube-tracker.py", line 65, in <module>
    rimg.analyze_file(args.filename)
  File "/usr/local/lib/python2.7/dist-packages/rubikscubetracker/__init__.py", line 1832, in analyze_file
    return self.analyze(webcam=False, cube_size=cube_size)
  File "/usr/local/lib/python2.7/dist-packages/rubikscubetracker/__init__.py", line 1669, in analyze
    self.get_black_border_width(webcam)
  File "/usr/local/lib/python2.7/dist-packages/rubikscubetracker/__init__.py", line 1220, in get_black_border_width     
    % (self.black_border_width, self.median_square_width)
AssertionError: black_border_width 75, median_square_width 33
```

![BricKuber_back_face](https://user-images.githubusercontent.com/4965628/77448800-9b524100-6dc7-11ea-9cd1-86b4d8741eb5.jpg)

**Comment by CleoQc** [comment]
anyone?

**Comment by dwalton76** [comment]
@CleoQc sorry, I missed this 2+ years ago :(  Let me know if you are still having issues.

**Comment by CleoQc** [comment]
Thanks @dwalton76 . This was for a client. A student who was running brikuber for a school presentation. I'm still curious as to why it would fail. I had tried a few things, but never got it to work.

**Comment by dwalton76** [comment]
I suspect those RedHat stickers on the white squares were the issue.  Those will make it more difficult to identify where the square boundaries are.

**Comment by CleoQc** [comment]
Could very well be. But other faces also had the stickers and were fine. However I don't recall if there was a face with a sticker next to a red square.  
I'll keep it in mind if we ever had another student with a similar problem.

Brikuber is a much liked high school project.
